# every docker compose file should start with what version is being used
# yml are similar to json files, but instead of declaring what type each data value is, yml reads each bit of data as a string and then sets it to a value
# yml also doesnt use commas, instead using new lines, and doesnt use brackets but indentation instead
# yml is slower than json which is why json is used for client / server due to its speed - whereas yml is used for configuration
version: "3.8"
# telling docker about different containers for the program
services: 
  #frontend:
  # add when frontend is done
  api:
    # can give properties here
    build: ./scraper_Scripts
    # define port mapping
    ports:
      - 5000:5000
    # enviroment variables
    environment:
      - DB_URL=Server=localhost;Database=moviedb;Pwd=cyaninessteep-risingshrewdom_4;
  db:
    # pull image
    image: mysql:latest
    # always restart if it fails
    restart: always
    # map to these ports
    ports:
      - 3307:3307
    environment:
      # database name
      MYSQL_DATABASE: movieDB
      # give the correct port to start the db on otherwise we get errors
      MYSQL_TCP_PORT: 3307
      # random autogenerated password for the database
      MYSQL_ROOT_PASSWORD: cyaninessteep-risingshrewdom_4
    volumes:
      # tells docker to look after this for us
      - db:/var/lib/mysql
      # initialises the sql table
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local