# syntax=docker/dockerfile:1
# base image of python, so this uses a slim version of python 3.10.6 which is what i developed the api on
FROM python:3.10.6-slim-buster

# download chromium from the source because html-requests doesnt work otherwise
RUN apt-get update
RUN apt install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
# copy everything from the current directory into a folder called app
COPY requirements.txt .
# download requirements
RUN pip install -r requirements.txt

# change directory
WORKDIR /scraper_scripts
# copy all into a folder
COPY . .
# expose port 5000
EXPOSE 5001:5001
# execute this command
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0", "--port=5001"]